---
title: "Host-Pathogen Sharing Workflow Data"
author: "Emily M. Lachtara"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(knitr)
library(kableExtra)

# Define color pallette
mypal <- palette(brewer.pal(n = 10, name = "Set3"))
binpal <- c('limegreen', 'gold', 'royalblue', 'gray60')

# Load in data
load("data/final.genus.rda")
load("data/final.species.rda")
load("data/raw/clean_pathogen.rda")
load("data/final.genus.p.rda")
load("data/path/genus.rda")
```

```{r FIG1}
# Plot of all bins with individual slopes
p1 <- bin_genus_all %>% 
  ggplot( aes(x = distance, y = shared.org))+
  geom_point(aes(col = bin), alpha = 1, size = 3)+
  geom_smooth(aes(col = bin), method = "lm", se = FALSE, lwd = 0.7)+
  geom_smooth(method = "lm", se = FALSE, lwd = 0.5, col = "black", linetype = "dashed")+
  ggpubr::theme_pubr() +
  scale_colour_manual(values = binpal)+
  labs(y = "Proportion Pathogens Shared", x = "Phylogenetic Distance", col = "Tropic Bin")+
  labs(title = "Pathogen sharing vs. Distance (Genus-Genus)")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.text = element_text(size = 8),
        plot.title = element_blank(),
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position = "bottom")

ggsave("figures/BIN/genus.pdf",
       plot = p1,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)

# Split up data by bin
spl <- with(bin_genus_all, split(bin_genus_all, list(bin = bin)))

# nonpathogenic
nonpathogenic.slr <- lm(shared.org ~ distance, data = spl[["Non-pathogenic"]])
nonpathogenic.mlr <- lm(shared.org ~ distance + WOS, data = spl[["Non-pathogenic"]])
nonpathogenic.coef <- c("Non-pathogenic", confint(nonpathogenic.slr)[2], as.numeric(coef(nonpathogenic.slr)[2]), confint(nonpathogenic.slr)[4])
nonpathogenic.mlr.coef <- c("Non-pathogenic", confint(nonpathogenic.mlr)[2], # lower
                            as.numeric(coef(nonpathogenic.mlr)[2]), #distance
                            confint(nonpathogenic.mlr)[5], # upper
                            summary(nonpathogenic.mlr)$coefficients[c(11, 6, 12)]) # p, WOS, p2

# hemitrophic
hemitrophic.slr <- lm(shared.org ~ distance, data = spl[["Hemitrophic"]])
hemitrophic.mlr <- lm(shared.org ~ distance + WOS, data = spl[["Hemitrophic"]])
hemitrophic.coef <- c("Hemitrophic", confint(hemitrophic.slr)[2], as.numeric(coef(hemitrophic.slr)[2]), confint(hemitrophic.slr)[4])
hemitrophic.mlr.coef <- c("Hemitrophic", confint(hemitrophic.mlr)[2], # lower
                            as.numeric(coef(hemitrophic.mlr)[2]), #distance
                            confint(hemitrophic.mlr)[5], # upper
                            summary(hemitrophic.mlr)$coefficients[c(11, 6, 12)]) # p, WOS, p2

# necrotrophic
necrotrophic.slr <- lm(shared.org ~ distance, data = spl[["Necrotrophic"]])
necrotrophic.mlr <- lm(shared.org ~ distance + WOS, data = spl[["Necrotrophic"]])
necrotrophic.coef <- c("Necrotrophic", confint(necrotrophic.slr)[2], as.numeric(coef(necrotrophic.slr)[2]), confint(necrotrophic.slr)[4])
necrotrophic.mlr.coef <- c("Necrotrophic", confint(necrotrophic.mlr)[2], # lower
                            as.numeric(coef(necrotrophic.mlr)[2]), #distance
                            confint(necrotrophic.mlr)[5], # upper
                            summary(necrotrophic.mlr)$coefficients[c(11, 6, 12)]) # p, WOS, p2

# biotrophic
biotrophic.slr <- lm(shared.org ~ distance, data = spl[["Biotrophic"]])
biotrophic.mlr <- lm(shared.org ~ distance + WOS, data = spl[["Biotrophic"]])
biotrophic.coef <- c("Biotrophic", confint(biotrophic.slr)[2],  as.numeric(coef(biotrophic.slr)[2]), confint(biotrophic.slr)[4])
biotrophic.mlr.coef <- c("Biotrophic", confint(biotrophic.mlr)[2], # lower
                            as.numeric(coef(biotrophic.mlr)[2]), #distance
                            confint(biotrophic.mlr)[5], # upper
                            summary(biotrophic.mlr)$coefficients[c(11, 6, 12)]) # p, WOS, p2

# Join together slr coefficients
slr.coefs <- rbind(nonpathogenic.coef, hemitrophic.coef, necrotrophic.coef, biotrophic.coef) %>% as.data.frame() 
colnames(slr.coefs) <- c('bin', 'lower', 'distance', 'upper')
slr.coefs <- slr.coefs %>% mutate(lower = as.numeric(substr(lower, 1, 5))) %>% 
  mutate(distance =  as.numeric(substr(distance, 1, 5))) %>% 
  mutate(upper =  as.numeric(substr(upper, 1, 5)))
slr.coefs$mod <- "SLR"

# join together mlr coefficients
mlr.coefs <- rbind(nonpathogenic.mlr.coef, hemitrophic.mlr.coef, necrotrophic.mlr.coef, biotrophic.mlr.coef) %>% as.data.frame() 
colnames(mlr.coefs) <- c('bin', 'lower', 'distance', 'upper', 'p', 'WOS', 'p2')
mlr.coefs$mod <- "MLR"
mlr.coefs <- mlr.coefs %>% mutate(lower = as.numeric(substr(lower, 1, 5))) %>% 
  mutate(distance =  as.numeric(substr(distance, 1, 5))) %>% 
  mutate(upper =  as.numeric(substr(upper, 1, 5)))

# Coef plot + CI
p2 <- rbind(slr.coefs, mlr.coefs[,c(1:4, 8)]) %>%
ggplot(aes(x = reorder(bin, distance), y = distance, col = as.factor(bin))) +
  geom_errorbar(aes(ymin = lower, ymax = upper, linetype = as.factor(mod)), position = "dodge", width = 0.5, size = 1) + 
  #geom_point(aes(x = reorder(bin, distance), y = distance),  size = 5)+
  ggpubr::theme_pubr()+
  scale_colour_manual(values = binpal)+
  labs(y = "Distance Coefficient", col = "Trophic Bin", linetype = "Model")+
  labs(title = "Pathogen sharing vs. Distance by trophic Bin")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.title = element_blank(),
        legend.position = "right")

ggsave("figures/BIN/genus.coef.pdf",
       plot = p2,
       units = "in",
       width = 8,
       height = 3,
       useDingbats = FALSE)
```

```{r FIG1A}
load("data/final.genus.rda")
load("data/final.species.rda")

# Genus + species plot
genus_all$group = "Genus"
species_all$group = "Species"

p <- rbind(species_all, genus_all) %>% 
  group_by(host) %>% 
  summarize(PSR = n(), WOS = WOS, group = group) %>%
  distinct() %>%
  ggplot(aes(x = log(WOS), y = log(PSR), col = group)) +
  geom_point(size = 3)+
  scale_colour_manual(values = binpal[2:3])+
  geom_smooth(aes(group = group), method = "lm", se = FALSE, size = 0.5)+
  theme_minimal()+
  labs(y = "log(PSR)", x = "log(WOS Citations)", col = "taxonomy level")+
  labs(title = "WOS Citations vs PSR")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        #plot.title = element_blank(),
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position = "bottom")

ggsave("figures/PSR/fin.both.pdf",
       plot = p,
       units = "in",
       width = 4,
       height = 4,
       useDingbats = FALSE)

 
# RAW
load("data/raw/clean_pathogen.rda")

# Genus + species plot
genus_genus$group = "Genus"
species_species$group = "Species"

p2 <- rbind(species_species, genus_genus) %>% 
  group_by(host) %>% 
  summarize(PSR = n(), WOS = WOS, group = group) %>%
  distinct() %>%
  ggplot(aes(x = log(WOS), y = log(PSR), col = group)) +
  geom_point(size = 3)+
  scale_colour_manual(values = binpal[2:3])+
  geom_smooth(aes(group = group), method = "lm", se = FALSE, size = 0.5)+
  theme_minimal()+
  labs(y = "log(PSR)", x = "log(WOS Citations)", col = "Taxonomy Level")+
  labs(title = "WOS Citations vs PSR")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.title = element_blank(),
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position = "bottom")

ggsave("figures/PSR/raw.both.pdf",
       plot = p2,
       units = "in",
       width = 4,
       height = 4,
       useDingbats = FALSE)

#  Proportion vs. Distance Boxplots

binpalex <- c('firebrick',binpal)

# Species plot
p1 <- species_all %>% 
  filter(shared.org > 0) %>%
  ggplot(aes(x = as.factor(distance), y = shared.org)) +
  geom_boxplot(aes(fill = as.factor(distance)))+
  theme_minimal()+
  scale_fill_manual(values = binpalex)+
  labs(y = "Proportion Pathogens Shared", x = "Taxonomic Distance")+
  labs(title = "Species")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        #plot.title = element_blank(),
        legend.position = "none")

ggsave("figures/BOX/species.pdf",
       plot = p1,
       units = "in",
       width = 5,
       height = 4,
       useDingbats = FALSE)

# Genus plot
p2 <- genus_all %>% 
  filter(shared.org > 0) %>%
  ggplot(aes(x = as.factor(distance), y = shared.org)) +
  geom_boxplot(aes(fill = as.factor(distance)))+
  theme_minimal()+
  scale_fill_manual(values = binpalex)+
  labs(y = "Proportion Pathogens Shared", x = "Taxonomic Distance")+
  labs(title = "Genus")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        #plot.title = element_blank(),
        legend.position = "none")


ggsave("figures/BOX/genus.pdf",
       plot = p2,
       units = "in",
       width = 5,
       height = 4,
       useDingbats = FALSE)
```

```{r FAM }
load("data/final.genus.p.rda")
p <- genus_all.p %>%
  filter(hostfam != 0) %>%
  ggplot( aes(x = distance, y = shared.org)) +
  geom_point(aes(col =  hostfam), alpha = 0.8) +
  geom_smooth(aes(col = hostfam), method = "lm", se = FALSE, lwd = 0.7) +
  facet_wrap(~ hostfam) +
  ggpubr::theme_pubr() +
  scale_colour_manual(values = binpal)+
  labs(y = "Proportion Pathogens Shared", x = "Phylogenetic Distance", col = "family")+
  labs(title = "Pathogen sharing vs. Distance (Genus-Genus)")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.text = element_text(size = 8),
        plot.title = element_blank(),
        legend.position = "bottom")

ggsave("figures/FAM/genus.pdf",
       plot = p,
       units = "in",
       width = 10,
       height = 6,
       useDingbats = FALSE)

# Split up data by fam
spl <- with(genus_all.p, split(genus_all.p, list(bin = hostfam)))

# Caryophyllaceae
caryophyllaceae.slr <- lm(shared.org ~ distance, data = spl[["Caryophyllaceae"]])
caryophyllaceae.coef<- c("Caryophyllaceae", confint(caryophyllaceae.slr)[2], as.numeric(coef(caryophyllaceae.slr)[2]), confint(caryophyllaceae.slr)[4])

# Amaranthaceae
amaranthaceae.slr <- lm(shared.org ~ distance, data = spl[["Amaranthaceae"]])
amaranthaceae.coef<- c("Amaranthaceae", confint(amaranthaceae.slr)[2], as.numeric(coef(amaranthaceae.slr)[2]), confint(amaranthaceae.slr)[4])

# Polygonaceae
polygonaceae.slr <- lm(shared.org ~ distance, data = spl[["Polygonaceae"]])
polygonaceae.coef<- c("Polygonaceae", confint(polygonaceae.slr)[2], as.numeric(coef(polygonaceae.slr)[2]), confint(polygonaceae.slr)[4])

# Join together coefficients
slr.coefs <- rbind(polygonaceae.coef , amaranthaceae.coef, caryophyllaceae.coef) %>% as.data.frame() 
colnames(slr.coefs) <- c('fam', 'lower', 'distance', 'upper')
slr.coefs <- slr.coefs %>% mutate(lower = as.numeric(substr(lower, 1, 5))) %>% 
  mutate(distance =  as.numeric(substr(distance, 1, 5))) %>% 
  mutate(upper =  as.numeric(substr(upper, 1, 5)))

# Coef plot + CI
p2 <- ggplot(slr.coefs, aes(x = reorder(fam, distance), y = distance, col = as.factor(fam))) +
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.5, size = 1) + 
  geom_point(aes(x = reorder(fam, distance), y = distance), size = 5)+
  ggpubr::theme_pubr()+
  scale_colour_manual(values = binpal)+
  labs(y = "Distance Coefficient", x = "Family")+
  labs(title = "Pathogen sharing vs. Distance by Family")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.title = element_blank(),
        legend.position = "none")

ggsave("figures/FAM/genus.coef.pdf",
       plot = p2,
       units = "in",
       width = 8,
       height = 3,
       useDingbats = FALSE)
```

```{r RES}
# Residuals over search effort
bin.slr <- lm(shared.org ~ distance, data = bin_genus_all)
bin_genus_all$res <- resid(bin.slr)
p <- ggplot(bin_genus_all, aes( x = WOS, y = res, col = bin ))+
  geom_point(aes(col = bin), alpha = 1, size = 3)+
  geom_hline(yintercept = 0)+
  ggpubr::theme_pubr() +
  scale_colour_manual(values = binpal)+
  labs(y = "Residuals", x = "Search effort (citations)", col = "Tropic Bin")+
  labs(title = "Residuals plot sharing ~ distance")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.text = element_text(size = 8),
        #plot.title = element_blank(),
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position = "bottom")

ggsave("figures/RES/WOS.pdf",
       plot = p,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)


# Residuals over distance
bin.slr2 <- lm(shared.org ~ WOS, data = bin_genus_all)
bin_genus_all$res2 <- resid(bin.slr2)
p2 <-ggplot(bin_genus_all, aes( x = distance, y = res2, col = bin ))+
  geom_point(aes(col = bin), alpha = 1, size = 3)+
  geom_hline(yintercept = 0)+
  ggpubr::theme_pubr() +
  scale_colour_manual(values = binpal)+
  labs(y = "Residuals", x = "Phylogenetic Distance", col = "Tropic Bin")+
  labs(title = "Residuals plot sharing ~ search effort")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.text = element_text(size = 8),
        #plot.title = element_blank(),
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position = "bottom")

ggsave("figures/RES/distance.pdf",
       plot = p2,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)
```




```{r Genus Phylogeny}
# Model
genus.mod <- summary(lm(shared.org ~ distance, data = genus_all.p))
genus.mod.coefs <- cbind('All', genus.mod$coefficients[2], genus.mod$coefficients[8]) %>% as.data.frame()
colnames(genus.mod.coefs) <- c('Model', 'Coef', 'p')

# Genus plot phylogeny
p <- genus_all.p %>% 
  filter(shared.org > 0) %>%
  ggplot(aes(x = distance, y = shared.org)) +
  geom_smooth(method = "lm", se = FALSE, color = "black", lwd = 0.5)+
  theme_minimal()+
  labs(y = "Proportion Pathogens Shared", x = "Phylogenetic Distance")+
  labs(title = "Pathogen sharing vs. Distance (Genus-Genus)")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        #axis.title.y = element_text(size = 12, face = "bold"),
       # axis.title.x = element_text(size = 12, face = "bold"),
        plot.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.position = "none")

ggsave("figures/DOT/genus.pdf",
       plot = p,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)


# Run regression
mylm <- lm(shared.org ~ WOS + distance, genus_all.p)
predicted <- mylm %>% predict(genus_all.p)

# Species Prediction
spec_predict <- as.data.frame(cbind(genus_all.p$shared.org, predicted))

# Genus plot phylogeny
p2 <- ggplot(spec_predict, aes(x = V1, y = predicted)) +
  geom_point(col = mypal[1])+
  geom_smooth(method = "lm", se = FALSE, color = "black", lwd = 0.5)+
  theme_minimal()+
  labs(x = "True shared", y = "Predicted shared")+
  labs(title = "Shared.org ~ WOS + distance")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        #axis.title.y = element_text(size = 12, face = "bold"),
       # axis.title.x = element_text(size = 12, face = "bold"),
        plot.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.position = "none")

ggsave("figures/DOT/genus.mod.pdf",
       plot = p2,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)
```

```{r Trophic Bin}
# Update trophic bins to be less specific
bin_genus_all <- bin_genus_all %>% mutate(bin = case_when(
  (bin == 'N') ~ 'Necrotrophic',
  (bin == 'B') ~ 'Biotrophic',
  (bin %in% c('N/H','H', 'B/H')) ~ 'Hemitrophic',
  (bin %in% c('I', 'S', 'M', 'E')) ~ 'Non-pathogenic'))

#green (biotrophic),'forestgreen'
# yellow/orange ("hemibiotrophic") 'gold'
# and blue (necrotrophic) 'dodgerblue'
# grey (other) 'gray60'
mypal <- c('chartreuse4', 'gold', 'cornflowerblue', 'gray60')

p1 <- bin_genus_all %>% 
  ggplot( aes(x = distance, y = shared.org))+
  geom_point(aes(col = bin), alpha = 0.8)+
  geom_smooth(aes(col = bin), method = "lm", se = FALSE, lwd = 0.7)+
  geom_smooth(method = "lm", se = FALSE, lwd = 0.5, col = "black", linetype = "dashed")+
  ggpubr::theme_pubr() +
  scale_colour_manual(values = mypal)+
  labs(y = "Proportion Pathogens Shared", x = "Phylogenetic Distance", col = "Tropic Bin")+
  labs(title = "Pathogen sharing vs. Distance (Genus-Genus)")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.text = element_text(size = 8),
        plot.title = element_blank(),
        #axis.title.x = element_blank(),
        #axis.title.y = element_blank(),
        legend.position = "bottom")

ggsave("figures/BIN/genus.pdf",
       plot = p1,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)

# Get coefficients by bin
spl <- with(bin_genus_all, split(bin_genus_all, list(bin = bin)))

coefLM <- function(x) {
  mod <- lm(shared.org ~ distance, data = x)
  c(summary(mod)$coefficients[2], summary(mod)$coefficients[8])
}

coefs <- sapply(spl, coefLM) %>% t() %>%  as.data.frame() %>% tibble::rownames_to_column() 
colnames(coefs) <- c('bin', 'coef', 'p')
#coefs$bin <-stringr::str_replace(rownames(coefs), ".distance", "")

p2 <- coefs %>% 
  ggplot(aes(x = reorder(bin, coef), y = coef, fill = as.factor(bin))) +
  geom_bar(stat = "identity", color = "black", 
           position = position_dodge()) +
  theme_minimal()+
  geom_text(aes(label = round(coef, 3)), vjust = -1)+
  scale_fill_manual(values = mypal)+
  labs(y = "Distance Coefficient", x = "Trophic Bin")+
  labs(title = "Pathogen sharing vs. Distance by trophic Bin")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 12, face = "bold"),
        axis.text.y = element_text(size = 12, face = "bold"),
        plot.title = element_blank(),
        legend.position = "none")

ggsave("figures/BIN/genus.coef.pdf",
       plot = p2,
       units = "in",
       width = 8,
       height = 3,
       useDingbats = FALSE)
```

```{r Phylo Tree}
# Read in and flip over axis
Phylogeny <- readxl::read_excel("data/phylo/Phylogeny.xlsx", col_names = FALSE)
genera <- Phylogeny$...1
tmp <- Phylogeny[,-1]
colnames(tmp) <- rownames(tmp) <- genera
tmp <- as.matrix(tmp)
diag(tmp) <- 0
tmp[upper.tri(tmp)] <- t(tmp)[upper.tri(tmp)]

my_dist_mat <- as.dist(tmp)

my_nj <- ape::nj(my_dist_mat)
pdf(file = "figures/TREE/genus.pdf", width = 7, height = 8)
plot(my_nj, "unrooted", cex = 0.4, edge.width = 0.3)
```

```{r Proportion vs. Distance Dist}
# Species plot
p1 <- species_all %>% 
  filter(shared.org > 0)%>% 
  ggplot(aes(x = shared.org, col = as.factor(distance))) +
  geom_density()+
  theme_minimal()+
  scale_colour_manual(values = mypal)+
  labs(x = "Proportion Pathogens Shared", col = "Distance" )+
  labs(title = "Pathogen sharing distribution (Species-Species)", col = "Phylogenetic Distance")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "bottom")
  

ggsave("figures/DIS/species.pdf",
       plot = p1,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)

# Species-genera plot
p1a <- species_genus_all %>% 
  filter(shared.org > 0)%>% 
  ggplot(aes(x = shared.org, col = as.factor(distance))) +
  geom_density()+
  theme_minimal()+
  scale_colour_manual(values = mypal)+
  labs(x = "Proportion Pathogens Shared", col = "Distance" )+
  labs(title = "Pathogen sharing distribution (Species-Genus)", col = "Phylogenetic Distance")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "bottom")
  

ggsave("figures/DIS/species.gen.pdf",
       plot = p1a,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)

# Genus plot
p2 <- genus_all %>% 
  filter(shared.org > 0)%>% 
  ggplot(aes(x = shared.org, col = as.factor(distance))) +
  geom_density()+
  theme_minimal()+
  scale_colour_manual(values = mypal)+
  labs(x = "Proportion Pathogens Shared", col = "Distance" )+
  labs(title = "Pathogen sharing distribution (Genus-Genus)", col = "Phylogenetic Distance")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "bottom")
  

ggsave("figures/DIS/genus.pdf",
       plot = p2,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)

# Genus-species plot
p2a <- genus_species_all %>% 
  filter(shared.org > 0)%>% 
  ggplot(aes(x = shared.org, col = as.factor(distance))) +
  geom_density()+
  theme_minimal()+
  scale_colour_manual(values = mypal)+
  labs(x = "Proportion Pathogens Shared", col = "Distance" )+
  labs(title = "Pathogen sharing distribution (Genus-Species)", col = "Phylogenetic Distance")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "bottom")
  

ggsave("figures/DIS/genus.sp.pdf",
       plot = p2a,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)
```


```{r Tables}
# tbl1
rbind(genus.mod.coefs, coefs) %>% 
  mutate(Coef = round(as.numeric(Coef), 4)) 
```

```{r non}
# Genus WOS plot
p1 <- genus_genus %>%
  select(host, WOS) %>%
  distinct(host, .keep_all = TRUE) %>%
  ggplot(aes(x = log(WOS))) +
  geom_density(fill = mypal[8])+
  theme_minimal()+
  labs(y = "Count", x = "log(WOS Citations)")+
  labs(title = "WOS Citations by Genus")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        #axis.title.y = element_text(size = 12, face = "bold"),
        #axis.title.x = element_text(size = 12, face = "bold"),
        plot.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")

ggsave("figures/NON/WOS/genus.pdf",
       plot = p1,
       units = "in",
       width = 3,
       height = 3,
       useDingbats = FALSE)

p2 <- species_species %>%
  select(host, WOS) %>%
  distinct(host, .keep_all = TRUE) %>%
  ggplot(aes(x = log(WOS))) +
  geom_density(fill = mypal[1])+
  theme_minimal()+
  labs(y = "Count", x = "log(WOS Citations)")+
  labs(title = "WOS Citations by Species")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        #axis.title.y = element_text(size = 12, face = "bold"),
        #axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        plot.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")

ggsave("figures/NON/WOS/species.pdf",
       plot = p2,
       units = "in",
       width = 2,
       height = 2,
       useDingbats = FALSE)

# Genus host, genus pathogen
p1 <- genus_all %>%
  filter(shared.org > 0) %>%
  ggplot(aes(x = shared.org))+
  geom_density(fill = mypal[8])+
  theme_minimal()+
  labs(y = "Count", x = "Proportion Shared")+
  labs(title = "Host pathogen sharing (Genus-Genus)")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        #axis.title.y = element_text(size = 12, face = "bold"),
        #axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        plot.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")

ggsave("figures/NON/JAC/genus.pdf",
       plot = p1,
       units = "in",
       width = 2,
       height = 2,
       useDingbats = FALSE)


# Species host, species pathogen
p2 <- species_all %>%
  filter(shared.org > 0) %>%
  ggplot(aes(x = shared.org))+
  geom_density(fill = mypal[1])+
  theme_minimal()+
  labs(y = "Count", x = "Proportion Shared")+
  labs(title = "Host pathogen sharing (Species-Species)")+
  theme(#plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        #axis.title.y = element_text(size = 12, face = "bold"),
        #axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        plot.title = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none")
ggsave("figures/NON/JAC/species.pdf",
       plot = p2,
       units = "in",
       width = 2,
       height = 2,
       useDingbats = FALSE)
```