---
title: "Host-Pathogen Sharing Workflow Data"
author: "Emily M. Lachtara"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load required packages
library(readxl)
library(janitor)
library(dplyr)
library(ggplot2)
library(tidyr)
library(kableExtra)
library(readxl)
library(readr)
source('functions/Sharing_index.R')

# Define color pallette
mypal <- cbind(palette(RColorBrewer::brewer.pal(n = 8, name = "Set2")),
               palette(RColorBrewer::brewer.pal(n = 12, name = "Paired")))
```

```{r Create sharing index}
# Load in clean data if needed
load("data/clean_pathogen.rda")

# Get pathogen sharing index
get_sharing(data = genus_genus, path_to_save = "data/sharing/genus.sharing.rda")
get_sharing(data = species_species, path_to_save = "data/sharing/species.sharing.rda")
get_sharing(data = genus_species, path_to_save = "data/sharing/genus.sp.sharing.rda")
get_sharing(data = species_genus, path_to_save = "data/sharing/species.gen.sharing.rda")
```

```{r Visualize WOS distribution}
# Load pathogen data
load("data/clean_pathogen.rda")

# Genus WOS plot
p1 <- genus_genus %>%
  select(host, WOS) %>%
  distinct(host, .keep_all = TRUE) %>%
  ggplot(aes(x = log(WOS))) +
  geom_density(fill = mypal[9])+
  theme_minimal()+
  labs(y = "Count", x = "log(WOS Citations)")+
  labs(title = "WOS Citations by Genus")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")

ggsave("figures/WOS/genus.pdf",
       plot = p1,
       units = "in",
       width = 6,
       height = 5,
       useDingbats = FALSE)

p2 <- species_species %>%
  select(host, WOS) %>%
  distinct(host, .keep_all = TRUE) %>%
  ggplot(aes(x = log(WOS))) +
  geom_density(fill = mypal[13])+
  theme_minimal()+
  labs(y = "Count", x = "log(WOS Citations)")+
  labs(title = "WOS Citations by Species")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")

ggsave("figures/WOS/species.pdf",
       plot = p2,
       units = "in",
       width = 6,
       height = 5,
       useDingbats = FALSE)
```

```{r Visualize log(WOS) vs log(PSR)}
# Load pathogen data
load("data/clean_pathogen.rda")

# Species plot
p1 <- species_species %>% 
  group_by(host) %>% 
  summarize(PSR = n(), WOS = WOS) %>%
  ggplot(aes(x = log(WOS), y = log(PSR))) +
  geom_point(col = mypal[9], size = 1)+
  geom_smooth(method = "lm", se = FALSE, size = 0.3, col = mypal[9])+
  theme_minimal()+
  labs(y = "log(PSR)", x = "log(WOS Citations)")+
  labs(title = "WOS Citations vs PSR by species")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")

ggsave("figures/PSR/species.pdf",
       plot = p1,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)


# Genus plot
p2 <- genus_genus %>% 
  group_by(host) %>% 
  summarize(PSR = n(), WOS = WOS) %>%
  ggplot(aes(x = log(WOS), y = log(PSR))) +
  geom_point(col = mypal[15], size = 1)+
  geom_smooth(method = "lm", se = FALSE, size = 0.3, col = mypal[15])+
  theme_minimal()+
  labs(y = "log(PSR)", x = "log(WOS Citations)")+
  labs(title = "WOS Citations vs PSR by genus")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")

ggsave("figures/PSR/genus.pdf",
       plot = p2,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)

# Genus + species plot
genus_genus$group = "Genus"
species_species$group = "Species"
p3 <- rbind(species_species, genus_genus) %>% 
  group_by(host) %>% 
  summarize(PSR = n(), WOS = WOS, group = group) %>%
  ggplot(aes(x = log(WOS), y = log(PSR), col = group)) +
  geom_point(size = 1)+
  scale_colour_manual(values = mypal[3:4])+
  geom_smooth(method = "lm", se = FALSE, size = 0.3, col = mypal[2])+
  theme_minimal()+
  labs(y = "log(PSR)", x = "log(WOS Citations)", col = "taxonomy level")+
  labs(title = "WOS Citations vs PSR by genus")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "bottom")

ggsave("figures/PSR/both.pdf",
       plot = p3,
       units = "in",
       width = 6,
       height = 6,
       useDingbats = FALSE)
```

```{r Visualize pathogen sharing}
# Genus host, genus pathogen
load("data/sharing/genus.sharing.rda")
p1 <- as.data.frame(sharing) %>%
  mutate(percent = as.numeric(shared)/(as.numeric(org1.count) + as.numeric(org2.count))) %>%
  filter(percent > 0) %>% 
  ggplot(aes(x = percent))+
  geom_density(fill = mypal[8])+
  theme_minimal()+
  labs(y = "Count", x = "Jaccard Index")+
  labs(title = "Host pathogen sharing (Genus-Genus)")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
ggsave("figures/JAC/genus.genus.pdf",
       plot = p1,
       units = "in",
       width = 6,
       height = 5,
       useDingbats = FALSE)

# Genus host, species pathogen
load("data/sharing/genus.sp.sharing.rda")
p2 <- as.data.frame(sharing) %>%
  mutate(percent = as.numeric(shared)/(as.numeric(org1.count) + as.numeric(org2.count))) %>%
  filter(percent > 0) %>% 
  ggplot(aes(x = percent))+
  geom_density(fill = mypal[4])+
  theme_minimal()+
  labs(y = "Count", x = "Jaccard Index")+
  labs(title = "Host pathogen sharing (Genus-Species)")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
ggsave("figures/JAC/genus.sp.pdf",
       plot = p2,
       units = "in",
       width = 6,
       height = 5,
       useDingbats = FALSE)

# Species host, species pathogen
load("data/sharing/species.sharing.rda")
p3 <- as.data.frame(sharing) %>%
  mutate(percent = as.numeric(shared)/(as.numeric(org1.count) + as.numeric(org2.count))) %>%
  filter(percent > 0) %>% 
  ggplot(aes(x = percent))+
  geom_density(fill = mypal[2])+
  theme_minimal()+
  labs(y = "Count", x = "Jaccard Index")+
  labs(title = "Host pathogen sharing (Species-Species)")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
ggsave("figures/JAC/species.pdf",
       plot = p3,
       units = "in",
       width = 6,
       height = 5,
       useDingbats = FALSE)

# Species host, genus pathogen
load("data/sharing/species.gen.sharing.rda")
p4 <- as.data.frame(sharing) %>%
  mutate(percent = as.numeric(shared)/(as.numeric(org1.count) + as.numeric(org2.count))) %>%
  filter(percent > 0) %>% 
  ggplot(aes(x = percent))+
  geom_density(fill = mypal[1])+
  theme_minimal()+
  labs(y = "Count", x = "Jaccard Index")+
  labs(title = "Host pathogen sharing (Species-Genus)")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")
ggsave("figures/JAC/species.gen.pdf",
       plot = p4,
       units = "in",
       width = 6,
       height = 5,
       useDingbats = FALSE)
```

## Species Analysis

```{r Proportion vs WOS + Distance}
load("data/phylo/joined.species.rda")

# Run regression
mylm <- lm(shared.org ~ WOS + distance, species_all)
predicted <- mylm %>% predict(species_all)

# Species Prediction
spec_predict <- as.data.frame(cbind(species_all$shared.org, predicted))

summary(mylm)

ggplot(spec_predict, aes(x = V1, y = predicted))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()+
  labs(x = "True shared", y = "Predicted shared")+
  labs(title = "Shared.org ~ WOS + distance")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")

```

```{r Proportion vs. Distance}
# Plot proportion.org vs distance
load("data/phylo/joined.species.rda")

# Run regression
mylm2 <- lm(shared.org ~ distance, species_all)
predicted2 <- mylm2 %>% predict(species_all)

# Species Prediction
spec_predict2 <- as.data.frame(cbind(species_all$shared.org, predicted2))

summary(mylm2)

ggplot(spec_predict2, aes(x = V1, y = predicted2))+
  geom_point()+
  geom_smooth(method = "lm")+
  theme_minimal()+
  labs(x = "True shared", y = "Predicted shared")+
  labs(title = "Shared.org ~ WOS + distance")+
  theme(plot.title = element_text(hjust = 0.5, size = 13, face = "bold"),
        axis.title.y = element_text(size = 12, face = "bold"),
        axis.title.x = element_text(size = 12, face = "bold"),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        legend.position = "none")

```


